title: Subramanya N
email: subramanyanagabhushan@gmail.com
description: Welcome to my personal website, a space where I blog and share my musings on academic and professional topics. Dive in to explore my intellectual journey and gain insights from my experiences in various fields!
baseurl: ""
url: "https://subramanya.ai"
data_dir: _data

# Build settings
markdown: kramdown
permalink: pretty

# collections
collections:
  books:
    output: true

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

keep_files:
  - sitemap-media.xml

# Google Analytics
google_analytics: G-04B5H1S8SJ
google_optimize: OPT-PHBLQWB
